### ISSUE TITLE
Nice work! 一人血书求开源权重和模型!

### ISSUE THREAD

**Issue by StarCycle** [GR1-Manipulation/GR-1#1]
![image](https://github.com/GR1-Manipulation/GR-1/assets/33491471/f694caec-c52e-4fff-8b5e-e9ace5fda675)
一人血书求开源权重和模型！

**Comment by NirViaje** [comment]
哈哈哈笑死，我作证这哥们两个月前做了几乎一模一样的模型但是没训起来

**Comment by NirViaje** [comment]
就是收敛效果要打折扣，btw GR-1这个0shot能力还是挺好的

**Comment by wxz1996** [comment]
> 哈哈哈笑死，我作证这哥们两个月前做了几乎一模一样的模型但是没训起来

什么钞能力啊

**Comment by siaoliu** [comment]
论文1月就中了ICLR2024还不开源啊。。。又图个乐了

**Comment by roy5444546495** [comment]
@StarCycle 你复现了这个工作吗大佬 可以交流一下吗

**Comment by StarCycle** [comment]
@roy5444546495 @siaoliu @wxz1996 大家如果想一起交流的话可以加加群
![6852e1288d9cc2d0ccd11444608f0bb](https://github.com/GR1-Manipulation/GR-1/assets/33491471/ee4599c4-4dcf-4f0f-86bc-697ec0d0fe52)

**Comment by hongtaowu67** [comment]
让大家久等了。代码已经开源：https://github.com/bytedance/GR-1

**Comment by StarCycle** [comment]
@hongtaowu67 非常感谢！
